### PR TITLE
Group Feature

### LINKED ISSUE #9: Remove User from NRU Group via Package
In `Manage packages` > Either `Create subscription package` or `Edit subscription package` > `fieldset` of `Package groups` > Add `Remove from "Newly registered users" groups` :
~~Where `Select one or more groups to remove subscribers from.`~~

---

My(my friends forum) case scenario : 
Remove user from `Newly registered users` which has all the `Never` permissions...
When user subscribe's to one of the package , remove that user from `Newly registered users`.

~~Others case scenario : 
Remove user from any groups ({that may have `Never` permissions}), When user subscribe's to the package.~~

---

Of-course it should not display `Pre-defined groups` just like in `Package groups`,
exception to `Newly registered users` group.

---

~~Exceptional case scenario , where due to human error , people might select same groups in `Package groups` & `Remove form groups` ,
Then ignore those groups from `Remove from groups` .~~

---

Hoping that you consider this feature & see it realized. 😃 

Thanking you , Best regards 👍

### PR DESCRIPTION
**Pull request by dark-1**
- Add Permanent Group(s)
- Remove Permanent from "Newly registered users" Group
- Migration File which also handled previous Subscription
- Language File Update

Fix #9 

### Fully Working Code + Fully Tested

### CODE REVIEW

**Comment by dark-1** [comment]
@stevotvr ,

You can merge this.
Also let me know if any changes are required.

Best Regards 👍

**Comment by dark-1** [comment]
Screen Shot :

**Comment by dark-1** [comment]
@stevotvr ,

Anything required to be done by me?
Or your thoughts on this ?

Best regards 👍

**Comment by stevotvr** [comment]
I'm working on other projects right now. I'll look at this when I have time.

**Comment by dark-1** [comment]
Ok. Take your time.
Sooner the better to use this feature.

BTW this is version 1.1.1 , due to migration.

Best regards 👍

**Comment by dark-1** [comment]
@stevotvr ,

Anytime in this month, will it be scrutinized & merged ???
Coz , I would really love to have this feature used on Live forum.

Thanking you , Best regards 👍

**Comment by stevotvr** [comment]
The first version finally got approved for the Customization Database after a few tries. I just submitted 1.1.0 to the queue so I want to wait for that to be approved before adding any new features.

Also, I may want to take another approach that will be easier for the user to understand. It will have actions you can set for subscription start and end, each with groups to add and groups to remove. I also might want to add events to make it extensible.

**Comment by dark-1** [comment]
So in that case , you will add permanent group & remove **Newly registered users** group, right?

Best regards 👍

**Pull request closed without merging**
