### PR TITLE
Group Sets [ACP FrontEnd Only]

### LINKED ISSUE #9: Remove User from NRU Group via Package
In `Manage packages` > Either `Create subscription package` or `Edit subscription package` > `fieldset` of `Package groups` > Add `Remove from "Newly registered users" groups` :
~~Where `Select one or more groups to remove subscribers from.`~~

---

My(my friends forum) case scenario : 
Remove user from `Newly registered users` which has all the `Never` permissions...
When user subscribe's to one of the package , remove that user from `Newly registered users`.

~~Others case scenario : 
Remove user from any groups ({that may have `Never` permissions}), When user subscribe's to the package.~~

---

Of-course it should not display `Pre-defined groups` just like in `Package groups`,
exception to `Newly registered users` group.

---

~~Exceptional case scenario , where due to human error , people might select same groups in `Package groups` & `Remove form groups` ,
Then ignore those groups from `Remove from groups` .~~

---

Hoping that you consider this feature & see it realized. 😃 

Thanking you , Best regards 👍

### PR DESCRIPTION
**Pull request by dark-1**
- Add Permanent `group_type = 1`
- Add Temporally (Original Implementation) `group_type = 2`
- Remove Temporally `group_type = 3`
- Remove Permanent `group_type = 4`
- Migration File
- Language File

Group Sets for ACP FrontEnd Only,
Which takes Data & stores it to `groupsub_groups` table.

This partially fix #9

### Need to implement the core BackEnd ... To use `group_type` .
It's hard for me to understand `operator\subscription` ...

Best regards 👍

### CODE REVIEW

**Comment by dark-1** [comment]
@stevotvr ,

Kindly check this if it's right for the BackEnd to Handle Subscription : 
Commit : https://github.com/dark-1/phpbb-groupsub/commit/a735916b25393dae26e8dcf458014d7b71bc5995
My Branch : https://github.com/dark-1/phpbb-groupsub/tree/GrpSetSub

Kindly let me know if changes are required.... I did try...
My guess I have handled `add_user_to_group_sets` Properly.
But I am not so sure if I handled `remove_user_from_group_sets` Properly... It's confusing for me...

Thanking you , Best regards 👍

**Comment by stevotvr** [comment]
I don't really have time to work on this right now, so it will probably have to wait until 1.2.0.

**Comment by dark-1** [comment]
Ok.

But there is a Migration file depending on v1.1.0 also latest file is v1.1.1 , just for your Info...

Thanking you , Best regards 👍

**Comment by dark-1** [comment]
Became too complex for BackEnd in Function `remove_user_from_group_sets` of `operator\subscription`.

**Pull request closed without merging**
