### PR TITLE
Fix Term Table.

### PR DESCRIPTION
**Pull request by dark-1**
Fix irregular column width & responsive rendering on mobile device of Term table.

### CODE REVIEW

**Comment by dark-1** [comment]
Resolved by c85d299e71b45f661f88da3f36a26183b419ad4f

**Comment by stevotvr** [comment]
I added the responsive headers and noticed a bug in the process. The phpBB responsive JavaScript seems to be adding the headers from both the inner and outer tables. I'm not sure what to do about this.

**Comment by dark-1** [comment]
Just do what I did, that bug will be fixed by them.

Best regards 👍

**Comment by dark-1** [comment]
Well !!! I investigated further...
you have 3 options :
1. turn the first table to `non-responsive`.
2. Add the `thead` to with `style="display: none;"` & wait till someone make a PR to fix that JQ issue.
3. Don't use table inside table. {recommended to use `div`}

Best regards 👍

**Comment by dark-1** [comment]
@stevotvr ,
try this for 3rd option from above comment : 
```html
<td>
{% if p.term %}
	{% for t in p.term|slice(0, 4) %}
		<div style="border: 3px solid transparent;">
			<div style="display:inline-block; width:50%;">{{ t.PRICE }}</div>
			<div style="display:inline-block;">{% if t.LENGTH %}{{ t.LENGTH }}{% else %}<i>{{ lang('ACP_GROUPSUB_EXPIRES_UNLIMITED') }}</i>{% endif %}</div>
		</div>
	{% endfor %}
	{% if p.term|length > 4 %}
		<div style="border: 3px solid transparent;">{{ lang('ACP_GROUPSUB_MORE', p.term|length - 4) }}</div>
	{% endif %}
{% endif %}
</td>
```
can you your own styling...

Best regards 👍

**Comment by dark-1** [comment]
@stevotvr ,

Or if you prefer very close to table style : 
Template file : 
```html
<td>
{% if p.term %}
	<div class="divtable">
		{% for t in p.term|slice(0, 4) %}
			<div class="divtr">
				<div class="divtd divtd1">{{ t.PRICE }}</div>
				<div class="divtd divtd2">{% if t.LENGTH %}{{ t.LENGTH }}{% else %}<i>{{ lang('ACP_GROUPSUB_EXPIRES_UNLIMITED') }}</i>{% endif %}</div>
			</div>
		{% endfor %}
		{% if p.term|length > 4 %}
			<div class="divtr divtrtd">{{ lang('ACP_GROUPSUB_MORE', p.term|length - 4) }}</div>
		{% endif %}
	</div>
{% endif %}
</td>
```

CSS file : 
```css
.divtable {
	border: 1px solid #000000;
	border-radius: 5px;
}

.divtr {
	border-bottom: 1px solid #000000;
}

.divtrtd {
	padding: 5px;
	display:block;
}

.divtd {
	padding: 5px;
	display:inline-block;
}

.divtd1 {
	width:50%;
}

.divtd2 {
	border-left: 1px solid #000000;
}
```

Best regards 👍

**Pull request closed without merging**
